DO $$ BEGIN END; $$ LANGUAGE PLPGSQL; --for github indexing

SELECT * FROM ESTATISTICA_JOGO;
SELECT * FROM ESTATISTICA_JOGADOR;
SELECT * FROM PONTUACAO_JOGADOR;
SELECT * FROM PARTIDA_MULTIJOGADOR;
SELECT * FROM PARTIDA_NORMAL;
SELECT * FROM PARTIDA;
SELECT * FROM CRACHAS_ATRIBUIDOS;
SELECT * FROM CRACHA;
SELECT * FROM COMPRA;
SELECT * FROM JOGO;
SELECT * FROM CHATS;
SELECT * FROM CHAT_GROUP_PARTICIPANT;
SELECT * FROM CHAT_GROUP;
SELECT * FROM AMIGOS;
SELECT * FROM JOGADOR;
SELECT * FROM REGIAO;