/* NOTES
- BY DEFAULT AS IDENTIFY - https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/#:~:text=issue%20an%20error.-,The%20GENERATED%20BY%20DEFAULT,-also%20instructs%20PostgreSQL
- Reserved keywords - https://www.postgresql.org/docs/current/sql-keywords-appendix.html
- TIMESTAMP - https://www.postgresql.org/docs/current/datatype-datetime.html
*/

CREATE TABLE JOGADOR(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    estado TEXT NOT NULL CHECK(estado IN ('Ativo', 'Inativo', 'Banido')),
    regiao TEXT NOT NULL CHECK(estado IN ('EU', 'NA', 'ASIA'))
);

CREATE TABLE JOGO(
    id CHAR(10) PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, --AKA referencia
    url TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL UNIQUE
);

CREATE TABLE COMPRA(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataa TIMESTAMP NOT NULL,
    preco DECIMAL(6, 2) -- Up to 1000.00
    id_jogador INT NOT NULL,
    id_jogo CHAR(10) NOT NULL,
    CONSTRAINT fk_id_jogador FOREIGN KEY id_jogador REFERENCES JOGADOR(id),
    CONSTRAINT fk_id_jogo FOREIGN KEY id_jogo REFERENCES JOGO(id)
);

CREATE TABLE CRACHA(
    id_jogador INT NOT NULL
    id_jogo CHAR(10) NOT NULL
    nome TEXT NOT NULL,
    pontos INT NOT NULL,
    url TEXT NOT NULL,
    CONSTRAINT fk_id_jogador FOREIGN KEY id_jogador REFERENCES JOGADOR(id),
    CONSTRAINT fk_id_jogo FOREIGN KEY id_jogo REFERENCES JOGO(id),
    PRIMARY KEY(id_jogador, id_jogo, nome)
);