--Deletes tables (and removes data)

DROP PROCEDURE IF EXISTS criarJogador;
DROP PROCEDURE IF EXISTS mudarEstadoJogador;
DROP FUNCTION IF EXISTS getTotalPointsOfPlayer;
DROP FUNCTION IF EXISTS getTotalGamesOfJogador;

DROP TABLE IF EXISTS ESTATISTICA_JOGO;
DROP TABLE IF EXISTS ESTATISTICA_JOGADOR;
DROP TABLE IF EXISTS PONTUACAO_JOGADOR;
DROP TABLE IF EXISTS PARTIDA_MULTIJOGADOR;
DROP TABLE IF EXISTS PARTIDA_NORMAL;
DROP TABLE IF EXISTS PARTIDA;
DROP TABLE IF EXISTS CRACHAS_ATRIBUIDOS;
DROP TABLE IF EXISTS CRACHA;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS CHATS;
DROP TABLE IF EXISTS CHAT_GROUP_PARTICIPANT;
DROP TABLE IF EXISTS CHAT_GROUP;
DROP TABLE IF EXISTS AMIGOS;
DROP TABLE IF EXISTS JOGADOR;
DROP TABLE IF EXISTS REGIAO;

DROP TYPE IF EXISTS regiao_enum;
DROP TYPE IF EXISTS estado_enum;
